#Sugarcane Pot Mod Configuration
#growth_chance: Chance de croissance (1 chance sur X) - défaut: 3
#min_drop: Nombre minimum de cannes récoltées - défaut: 1
#max_drop: Nombre maximum de cannes récoltées - défaut: 2
#allow_bonemeal: Permettre l'utilisation de poudre d'os - défaut: false
#show_particles: Afficher des particules lors de la croissance - défaut: true
#Wed Feb 25 13:44:44 CET 2026
allow_bonemeal=true
growth_chance=3
max_drop=2
min_drop=1
show_particles=true
